"""Planner Agent - Converts user input into a step-by-step execution plan."""

from typing import Any

from pydantic import BaseModel, Field

from llm import LLMClient
from tools import BaseTool

from .base_agent import BaseAgent


class PlanStep(BaseModel):
    """A single step in the execution plan."""

    step_number: int = Field(description="Step number in sequence")
    description: str = Field(description="What this step does")
    tool: str = Field(description="Name of the tool to use")
    parameters: dict[str, Any] = Field(description="Parameters to pass to the tool")
    depends_on: list[int] = Field(
        default_factory=list,
        description="Step numbers this step depends on",
    )


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by the Planner."""

    task_summary: str = Field(description="Brief summary of the user's task")
    steps: list[PlanStep] = Field(description="Ordered list of execution steps")
    expected_output: str = Field(description="Description of expected final output")


class PlannerAgent(BaseAgent):
    """Agent responsible for planning task execution."""

    name = "planner"

    def __init__(self, llm_client: LLMClient, tools: list[BaseTool]):
        super().__init__(llm_client)
        self.tools = {tool.name: tool for tool in tools}

    def _get_tools_description(self) -> str:
        """Generate description of available tools for the LLM."""
        tool_descriptions = []
        for tool in self.tools.values():
            info = tool.get_tool_info()
            tool_descriptions.append(
                f"- **{info['name']}**: {info['description']}\n"
                f"  Parameters: {info['parameters']}"
            )
        return "\n".join(tool_descriptions)

    async def run(self, user_task: str, **kwargs) -> ExecutionPlan:
        """Generate an execution plan for the user's task."""
        system_prompt = """You are a planning agent that creates step-by-step execution plans.
Your job is to analyze user tasks and break them down into concrete steps using available tools.

Rules:
1. Only use tools from the available tools list
2. Each step must have a specific tool and parameters
3. Steps should be ordered logically
4. If a step depends on previous results, specify dependencies
5. Be specific with parameters - use exact values from the user's request
6. If the task cannot be accomplished with available tools, create a minimal plan and note limitations

You must return a valid JSON object matching this structure:
{{
    "task_summary": "Brief summary of the task",
    "steps": [
        {{
            "step_number": 1,
            "description": "Step description",
            "tool": "tool_name",
            "parameters": {{ "param_key": "param_value" }},
            "depends_on": []
        }}
    ],
    "expected_output": "Description of expected final output"
}}

Available Tools:
{tools}
"""

        prompt = f"""Create an execution plan for this task:

Task: {user_task}

Analyze the task and create a structured plan with specific steps.
Each step should specify which tool to use and with what parameters."""

        formatted_system = system_prompt.format(tools=self._get_tools_description())

        plan = self.llm.generate_structured(
            prompt=prompt,
            response_model=ExecutionPlan,
            system_prompt=formatted_system,
        )

        return plan
